php artisan make:model Badge
php artisan make:model BloodBank
php artisan make:model BloodBankContact
php artisan make:model BloodDrive
php artisan make:model BloodRequest
php artisan make:model BloodType
php artisan make:model Community
php artisan make:model Donation
php artisan make:model Donor
php artisan make:model Organization
php artisan make:model OrganizationContact
